package com.sudeepkarki.journalApp.repository;

import com.sudeepkarki.journalApp.entity.User;
import org.bson.types.ObjectId;
import org.springframework.data.mongodb.repository.MongoRepository;

public interface UserRepository extends MongoRepository<User, ObjectId> {
    // Conceptual MongoDB query generated by Spring Data
    // db.users.findOne({ "userName": "sudeep" })
    //Spring data generates the implementation for this method automatically

    User findByUserName(String username);

}
